# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_auto_20170411_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'get_latest_by': 'started', 'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='recording',
            name='created',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='duration',
        ),
        migrations.AddField(
            model_name='recording',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
