# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_auto_20170414_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='filesize',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
