# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0005_auto_20170502_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
