# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0006_recording_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recording',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recording',
            name='last_paused',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
