# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20170419_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roommembership',
            unique_together=set([('room', 'participant')]),
        ),
    ]
