# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20170419_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='peer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('s', 'signalling'), ('e', 'event'), ('j', 'join'), ('a', 'announce'), ('A', 'action'), ('l', 'leave')], max_length=1),
        ),
    ]
