# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20170420_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
