# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20170707_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommembership',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
